//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Time.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Time.Translations.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds a new segment..
        /// </summary>
        public static string AddSegmentTooltip {
            get {
                return ResourceManager.GetString("AddSegmentTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows / Disables moving the window..
        /// </summary>
        public static string AllowMoveLabel {
            get {
                return ResourceManager.GetString("AllowMoveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows / Disables resize..
        /// </summary>
        public static string AllowResizeLabel {
            get {
                return ResourceManager.GetString("AllowResizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show window always on top..
        /// </summary>
        public static string AlwaysOnTopLabel {
            get {
                return ResourceManager.GetString("AlwaysOnTopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string AppearanceLabel {
            get {
                return ResourceManager.GetString("AppearanceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto start up can be configured from Settings / Apps / Startup # Date &amp; time.
        /// </summary>
        public static string AutoStartUpLabel {
            get {
                return ResourceManager.GetString("AutoStartUpLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background color of the window..
        /// </summary>
        public static string BackgroundColorLabel {
            get {
                return ResourceManager.GetString("BackgroundColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opacity / Transparency of the background..
        /// </summary>
        public static string BackgroundOpacityLabel {
            get {
                return ResourceManager.GetString("BackgroundOpacityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseTooltip {
            get {
                return ResourceManager.GetString("CloseTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corner radius of the window..
        /// </summary>
        public static string CornerRadiusLabel {
            get {
                return ResourceManager.GetString("CornerRadiusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows the formating of time and date in any arbitrary order or separation simbols.
        ///Example:
        ///d, ddd, dddd, M, MM, MMM, MMMM, y, yyy
        ///will result in:
        ///23, Tue, Tuesday, 8, 08, Aug, August, 22, 2022.
        /// </summary>
        public static string CustomFormatDescription {
            get {
                return ResourceManager.GetString("CustomFormatDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom format.
        /// </summary>
        public static string CustomFormatLabel {
            get {
                return ResourceManager.GetString("CustomFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about formatting.
        /// </summary>
        public static string CustomFormattingDocsLabel {
            get {
                return ResourceManager.GetString("CustomFormattingDocsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string DateLabel {
            get {
                return ResourceManager.GetString("DateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string DayLabel {
            get {
                return ResourceManager.GetString("DayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        public static string FontLabel {
            get {
                return ResourceManager.GetString("FontLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply opacity to text..
        /// </summary>
        public static string FontOpacityLabel {
            get {
                return ResourceManager.GetString("FontOpacityLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string FontSizeLabel {
            get {
                return ResourceManager.GetString("FontSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color of text..
        /// </summary>
        public static string ForegroundColorLabel {
            get {
                return ResourceManager.GetString("ForegroundColorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format.
        /// </summary>
        public static string FormatLabel {
            get {
                return ResourceManager.GetString("FormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show me the code..
        /// </summary>
        public static string GithubLabel {
            get {
                return ResourceManager.GetString("GithubLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long date.
        /// </summary>
        public static string LongDateLabel {
            get {
                return ResourceManager.GetString("LongDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long day.
        /// </summary>
        public static string LongDayLabel {
            get {
                return ResourceManager.GetString("LongDayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long time.
        /// </summary>
        public static string LongTimeLabel {
            get {
                return ResourceManager.GetString("LongTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix (text shown before the segment).
        /// </summary>
        public static string PrefixLabel {
            get {
                return ResourceManager.GetString("PrefixLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the currently selected segment..
        /// </summary>
        public static string RemoveSegmentTooltip {
            get {
                return ResourceManager.GetString("RemoveSegmentTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resets the current settings to their default values..
        /// </summary>
        public static string ResetSettingsTooltip {
            get {
                return ResourceManager.GetString("ResetSettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsTooltip {
            get {
                return ResourceManager.GetString("SettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short date.
        /// </summary>
        public static string ShortDateLabel {
            get {
                return ResourceManager.GetString("ShortDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short day.
        /// </summary>
        public static string ShortDayLabel {
            get {
                return ResourceManager.GetString("ShortDayLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short time.
        /// </summary>
        public static string ShortTimeLabel {
            get {
                return ResourceManager.GetString("ShortTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the control buttons.
        /// </summary>
        public static string ShowButtonsLabel {
            get {
                return ResourceManager.GetString("ShowButtonsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show window in taskbar..
        /// </summary>
        public static string ShowInTaskbarLabel {
            get {
                return ResourceManager.GetString("ShowInTaskbarLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Love the thing, migh even get you a coffee!.
        /// </summary>
        public static string ShowLoveTooltip {
            get {
                return ResourceManager.GetString("ShowLoveTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix (text shown after the segment).
        /// </summary>
        public static string SuffixLabel {
            get {
                return ResourceManager.GetString("SuffixLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text only.
        /// </summary>
        public static string TextOnlyFormatLabel {
            get {
                return ResourceManager.GetString("TextOnlyFormatLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string TimeLabel {
            get {
                return ResourceManager.GetString("TimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time zone.
        /// </summary>
        public static string TimeZoneLabel {
            get {
                return ResourceManager.GetString("TimeZoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time.
        /// </summary>
        public static string TitleLabel {
            get {
                return ResourceManager.GetString("TitleLabel", resourceCulture);
            }
        }
    }
}
